deleted the '!== false' because we want to use phps inner workings
WildCodeSchool/tours-php-2009-project2-quizzy pull request #13
Opened 2020-11-10 13:27 UTC by LucyMerlier

we actually want a flexible check because php translates what we actually want as true and what we dont want as false

2020-11-12 09:46 UTC, Mgaren submitted a review, later dismissed

2020-11-13 10:28 UTC, RomainClair requested changes
Safer to user strict comparison instead of php tricky conversions

2020-11-13 10:45 UTC, Mgaren approved these changes

2020-11-13 10:48 UTC, RomainClair approved these changes

2020-11-13 10:48 UTC, merged