user5-add PR
WildCodeSchool/tours-php-2009-project2-quizzy pull request #14
Opened 2020-11-12 12:53 UTC by LucyMerlier

added a step by step form that lets the user add their own question and the associated choices to the database

2020-11-12 12:57 UTC, FLorianBlm submitted a review, later dismissed

2020-11-13 10:20 UTC, RomainClair requested changes
The 
- addForm/addQuestion
- addForm/addChoices
- addForm/setValidity
- addForm/afterSubmit 
are somehow unclear.
Wouldn't it be better to have :
-  question/add
 - choices/add
 - choices/valid
 - choices/submitted
routes ?

The addQuestion & addChoices could be merged.

2020-11-13 10:20 UTC, RomainClair commented on src/Controller/AddFormController.php
> +        }
a or (||) would have been shorter.

2020-11-13 10:20 UTC, RomainClair commented on src/Controller/AddFormController.php
> +        $numberOfChoices = $_POST['numberOfChoices'];
You should validate that number of choices is an integer

2020-11-18 13:02 UTC, FLorianBlm submitted a review, later dismissed

2020-11-18 13:25 UTC, RomainClair requested changes
The choicesVerifications method has nothing to do with the database so it's strange it is in the ChoiceManager.
May be it's time to introduce a ChoiceValidator class for choice validation purposes

2020-11-18 13:25 UTC, RomainClair commented on src/Model/QuestionManager.php
> +        if ($statement->bindValue('userQuestion', $userQuestion, \PDO::PARAM_STR) === false) {
You should do the bindValue twice for the same parameter/value

2020-11-18 13:25 UTC, RomainClair commented on src/Model/ChoiceManager.php
> +            || $statement->bindValue('question_id', $questionId, \PDO::PARAM_INT) === false
You shouldn't do the bindValue twice for same parameter/value

2020-11-18 13:25 UTC, RomainClair commented on src/Controller/QuestionController.php
> +            }
Seems useless because you will replace the $_SESSION['userQuestion'] value just afterwards

2020-11-18 13:25 UTC, RomainClair commented on src/Controller/QuestionController.php
> +            $_SESSION['numberOfChoices'] = $numberOfChoices;
Same as above

2020-11-18 13:25 UTC, RomainClair commented on src/Controller/ChoicesController.php
> +            }
Seems useless because you'll replace $_SESSION['userChoices'] value just afterwards

2020-11-18 13:50 UTC, FLorianBlm approved these changes

2020-11-18 13:52 UTC, RomainClair approved these changes

2020-11-18 13:52 UTC, merged