user3-winORfail pull request
WildCodeSchool/tours-php-2009-project2-quizzy pull request #6
Opened 2020-10-30 09:25 UTC by LucyMerlier

created scripts to display a win or fail message depending on the validity of the selected choice

2020-10-30 09:26 UTC, erguculu submitted a review, later dismissed

2020-10-30 09:47 UTC, RomainClair requested changes
It's probably not a good idea to check the answer on the front-end (client-side) using JS.
A smart guy will see that the right asnwers are in your webpage, because if i look at the value, i just have to always answer a choice with a 1 value.

You'll have to check the answer validity in the back-end (server-side) because you need to hide to the client which answer is the right one.

Maybe it'll be the time to split README.md into separate files
README.md to explain the project
INTALL.MD for how to install the project, may be with a "dev" part.

2020-11-03 13:26 UTC, FLorianBlm approved these changes, later dismissed

2020-11-04 10:08 UTC, RomainClair requested changes

2020-11-04 10:08 UTC, RomainClair commented on src/Controller/QuestionController.php
> +            $id = $_POST['choice'];
You probably should check also if it's an int

2020-11-04 10:08 UTC, RomainClair commented on src/Controller/QuestionController.php
> +            $choice = $choiceManager->selectOneById($id);
It's also possible that the choice id is not in the database.

2020-11-04 11:12 UTC, FLorianBlm submitted a review, later dismissed

2020-11-04 15:32 UTC, RomainClair requested changes

2020-11-04 15:32 UTC, RomainClair commented on src/Controller/QuestionController.php
> +            $id = $_POST['choice'];
And you probably could do all this using a single filter_input

2020-11-04 15:32 UTC, RomainClair commented on src/Controller/QuestionController.php
> +            if (in_array($id, $allChoices)) {
It's probably a better approach to select the choice with the given id a maybe get no result, than getting all the database then check if our value is in it.

2020-11-04 15:32 UTC, RomainClair commented on src/Model/ChoiceManager.php
> +        return $result;
You could have your result directly using the right FETCH_MODE

2020-11-05 09:18 UTC, FLorianBlm approved these changes, later dismissed
Nice done

2020-11-05 13:56 UTC, RomainClair requested changes
You're try cach in QuestionController::result() is probably useless

2020-11-05 13:56 UTC, RomainClair commented on src/Controller/QuestionController.php
> +            if ($id) {
You should probably check precisely ($id !== false for example) to avoid tricky type conversions

2020-11-05 13:56 UTC, RomainClair commented on src/Controller/QuestionController.php
> +                header("Location: index");
You should end the controller (and probably return an empty view) after a redirection header.

2020-11-05 13:56 UTC, RomainClair commented on src/Controller/QuestionController.php
> +                $choice = $choiceManager->selectOneById($id);
You could have a valid id (integer > 0) that is not in the table.
You should check that you get a real choice.

2020-11-05 15:14 UTC, FLorianBlm approved these changes

2020-11-06 08:19 UTC, RomainClair approved these changes

2020-11-06 08:19 UTC, merged